"""Minimal ctypes bindings for the Win32 APIs Bruno needs.

Kept separate from the hotkey logic so that ``hotkey.py`` reads as intent
rather than as FFI boilerplate, and so these declarations can be reused by
future Windows integrations (tray, single-instance lock, foreground detection).

Every prototype below sets ``argtypes`` and ``restype`` explicitly. On 64-bit
Windows, letting ctypes guess truncates pointers and handles to 32 bits, which
fails in ways that look like random corruption rather than a type error.
"""

from __future__ import annotations

import ctypes
from ctypes import wintypes as wt
from typing import Final

# --- Hook types ------------------------------------------------------------
WH_KEYBOARD_LL: Final = 13
HC_ACTION: Final = 0

# --- Window messages -------------------------------------------------------
WM_QUIT: Final = 0x0012
WM_KEYDOWN: Final = 0x0100
WM_KEYUP: Final = 0x0101
WM_SYSKEYDOWN: Final = 0x0104
WM_SYSKEYUP: Final = 0x0105

# ``WM_SYSKEYDOWN`` rather than ``WM_KEYDOWN`` arrives for any key pressed while
# Alt is held, which is precisely our case, so both must be handled.
KEY_DOWN_MESSAGES: Final = frozenset({WM_KEYDOWN, WM_SYSKEYDOWN})
KEY_UP_MESSAGES: Final = frozenset({WM_KEYUP, WM_SYSKEYUP})

# --- Virtual key codes -----------------------------------------------------
VK_SPACE: Final = 0x20
VK_LSHIFT: Final = 0xA0
VK_RSHIFT: Final = 0xA1
VK_LCONTROL: Final = 0xA2
VK_RCONTROL: Final = 0xA3
VK_LMENU: Final = 0xA4  # left Alt
VK_RMENU: Final = 0xA5  # right Alt

VK_BACK: Final = 0x08
VK_TAB: Final = 0x09
VK_RETURN: Final = 0x0D
VK_ESCAPE: Final = 0x1B
VK_PRIOR: Final = 0x21  # Page Up
VK_NEXT: Final = 0x22  # Page Down
VK_END: Final = 0x23
VK_HOME: Final = 0x24
VK_LEFT: Final = 0x25
VK_UP: Final = 0x26
VK_RIGHT: Final = 0x27
VK_DOWN: Final = 0x28
VK_F5: Final = 0x74
VK_CONTROL: Final = 0x11
VK_MENU: Final = 0x12  # Alt

ALT_KEYS: Final = frozenset({VK_LMENU, VK_RMENU})

# --- Hook event flags ------------------------------------------------------
# Set on events generated by SendInput rather than by a physical key. Bruno
# synthesises keystrokes to drive the browser, and without this its own hook
# would see them: pressing Alt+Left to go back would look like the user
# holding Alt, and could engage Bruno's own hotkey.
LLKHF_INJECTED: Final = 0x00000010

# --- Input synthesis -------------------------------------------------------
INPUT_KEYBOARD: Final = 1
KEYEVENTF_KEYUP: Final = 0x0002
KEYEVENTF_EXTENDEDKEY: Final = 0x0001

# Arrow keys, Page Up/Down, Home and End are "extended" keys, distinguished
# from their numeric-keypad twins by this flag. Omitting it makes some
# applications see the keypad version and ignore it.
EXTENDED_KEYS: Final = frozenset(
    {VK_PRIOR, VK_NEXT, VK_END, VK_HOME, VK_LEFT, VK_UP, VK_RIGHT, VK_DOWN}
)

# --- Signed pointer-width return type used by hook procedures --------------
LRESULT = ctypes.c_ssize_t
ULONG_PTR = ctypes.c_size_t


class KBDLLHOOKSTRUCT(ctypes.Structure):
    """Payload Windows passes to a low-level keyboard hook."""

    _fields_ = [
        ("vkCode", wt.DWORD),
        ("scanCode", wt.DWORD),
        ("flags", wt.DWORD),
        ("time", wt.DWORD),
        ("dwExtraInfo", ctypes.c_void_p),
    ]


class KEYBDINPUT(ctypes.Structure):
    """One synthesised key event."""

    _fields_ = [
        ("wVk", wt.WORD),
        ("wScan", wt.WORD),
        ("dwFlags", wt.DWORD),
        ("time", wt.DWORD),
        ("dwExtraInfo", ULONG_PTR),
    ]


class _INPUTUNION(ctypes.Union):
    # Only the keyboard arm is declared. The union is sized by its largest
    # member in the real header, so the padding below keeps INPUT the size
    # Windows expects.
    _fields_ = [("ki", KEYBDINPUT), ("_padding", ctypes.c_byte * 32)]


class INPUT(ctypes.Structure):
    """Argument to ``SendInput``."""

    _anonymous_ = ("u",)
    _fields_ = [("type", wt.DWORD), ("u", _INPUTUNION)]


HOOKPROC = ctypes.WINFUNCTYPE(LRESULT, ctypes.c_int, wt.WPARAM, wt.LPARAM)

user32 = ctypes.WinDLL("user32", use_last_error=True)
kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

user32.SetWindowsHookExW.argtypes = (ctypes.c_int, HOOKPROC, wt.HINSTANCE, wt.DWORD)
user32.SetWindowsHookExW.restype = wt.HHOOK

user32.UnhookWindowsHookEx.argtypes = (wt.HHOOK,)
user32.UnhookWindowsHookEx.restype = wt.BOOL

user32.CallNextHookEx.argtypes = (wt.HHOOK, ctypes.c_int, wt.WPARAM, wt.LPARAM)
user32.CallNextHookEx.restype = LRESULT

user32.GetMessageW.argtypes = (ctypes.POINTER(wt.MSG), wt.HWND, wt.UINT, wt.UINT)
user32.GetMessageW.restype = ctypes.c_int

user32.TranslateMessage.argtypes = (ctypes.POINTER(wt.MSG),)
user32.TranslateMessage.restype = wt.BOOL

user32.DispatchMessageW.argtypes = (ctypes.POINTER(wt.MSG),)
user32.DispatchMessageW.restype = LRESULT

user32.PostThreadMessageW.argtypes = (wt.DWORD, wt.UINT, wt.WPARAM, wt.LPARAM)
user32.PostThreadMessageW.restype = wt.BOOL

kernel32.GetCurrentThreadId.argtypes = ()
kernel32.GetCurrentThreadId.restype = wt.DWORD

user32.SendInput.argtypes = (wt.UINT, ctypes.POINTER(INPUT), ctypes.c_int)
user32.SendInput.restype = wt.UINT

user32.GetForegroundWindow.argtypes = ()
user32.GetForegroundWindow.restype = wt.HWND

user32.GetWindowTextW.argtypes = (wt.HWND, wt.LPWSTR, ctypes.c_int)
user32.GetWindowTextW.restype = ctypes.c_int

user32.GetClassNameW.argtypes = (wt.HWND, wt.LPWSTR, ctypes.c_int)
user32.GetClassNameW.restype = ctypes.c_int

user32.GetWindowThreadProcessId.argtypes = (wt.HWND, ctypes.POINTER(wt.DWORD))
user32.GetWindowThreadProcessId.restype = wt.DWORD

# Limited query rights are enough for the executable path and, unlike full
# query access, are granted for processes at the same integrity level without
# elevation.
PROCESS_QUERY_LIMITED_INFORMATION: Final = 0x1000

kernel32.OpenProcess.argtypes = (wt.DWORD, wt.BOOL, wt.DWORD)
kernel32.OpenProcess.restype = wt.HANDLE

kernel32.QueryFullProcessImageNameW.argtypes = (
    wt.HANDLE,
    wt.DWORD,
    wt.LPWSTR,
    ctypes.POINTER(wt.DWORD),
)
kernel32.QueryFullProcessImageNameW.restype = wt.BOOL

kernel32.CloseHandle.argtypes = (wt.HANDLE,)
kernel32.CloseHandle.restype = wt.BOOL


# --- Convenience wrappers --------------------------------------------------

_TEXT_BUFFER = 512


def foreground_window() -> int:
    """Handle of the window the user is currently working in, or 0."""
    return user32.GetForegroundWindow() or 0


def window_title(hwnd: int) -> str:
    """Title bar text of a window, or an empty string."""
    if not hwnd:
        return ""
    buffer = ctypes.create_unicode_buffer(_TEXT_BUFFER)
    user32.GetWindowTextW(hwnd, buffer, _TEXT_BUFFER)
    return buffer.value


def window_class(hwnd: int) -> str:
    """Window class name, which identifies the application more reliably
    than a title the user's own document can change."""
    if not hwnd:
        return ""
    buffer = ctypes.create_unicode_buffer(_TEXT_BUFFER)
    user32.GetClassNameW(hwnd, buffer, _TEXT_BUFFER)
    return buffer.value


def window_process_id(hwnd: int) -> int:
    """Process owning a window, or 0."""
    if not hwnd:
        return 0
    pid = wt.DWORD()
    user32.GetWindowThreadProcessId(hwnd, ctypes.byref(pid))
    return pid.value


def process_name(pid: int) -> str:
    """Executable file name of a process, lowercased, or an empty string.

    The only dependable way to tell what an application actually is. Window
    class is not enough: every Electron application, Visual Studio Code
    included, reports the same class as Chrome, so a check based on class
    alone would treat a code editor as a browser.
    """
    if not pid:
        return ""

    handle = kernel32.OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, False, pid)
    if not handle:
        return ""

    try:
        size = wt.DWORD(_TEXT_BUFFER)
        buffer = ctypes.create_unicode_buffer(_TEXT_BUFFER)
        if not kernel32.QueryFullProcessImageNameW(handle, 0, buffer, ctypes.byref(size)):
            return ""
        return buffer.value.rsplit("\\", 1)[-1].lower()
    finally:
        kernel32.CloseHandle(handle)


def send_keys(*combination: int) -> bool:
    """Press a set of keys together and release them in reverse order.

    ``send_keys(VK_MENU, VK_LEFT)`` is Alt+Left. Events are delivered to
    whichever window has focus; nothing here changes focus, deliberately.

    Returns:
        True if Windows accepted every event. A False here usually means a
        more privileged window has focus, which no amount of retrying fixes.
    """
    if not combination:
        return True

    events: list[INPUT] = []
    for key in combination:
        events.append(_key_event(key, down=True))
    for key in reversed(combination):
        events.append(_key_event(key, down=False))

    array = (INPUT * len(events))(*events)
    sent = user32.SendInput(len(events), array, ctypes.sizeof(INPUT))
    return sent == len(events)


def _key_event(key: int, *, down: bool) -> INPUT:
    flags = 0 if down else KEYEVENTF_KEYUP
    if key in EXTENDED_KEYS:
        flags |= KEYEVENTF_EXTENDEDKEY

    event = INPUT(type=INPUT_KEYBOARD)
    event.ki = KEYBDINPUT(wVk=key, wScan=0, dwFlags=flags, time=0, dwExtraInfo=0)
    return event
