services:
  - type: web
    name: jarvis
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements-cloud.txt
    startCommand: python run.py
    envVars:
      - key: ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PROXY_SECRET
        value: jarvis-proxy-sec-9f8d7c6b5a4
      - key: AGENTROUTER_BASE_URL
        value: https://agentrouter.org/v1
      - key: GOOGLE_TOKEN_B64
        value: eyJ0b2tlbiI6ICJ5YTI5LmEwQVJHbnUwYThEWHZURkxDcDYtVWlMRVZXWG9XWFlTVkFTOEVNMEsxdzZEd0Q5c1NqOFd2d0ZVVHFhQ09acmRMSWpyWnlaYWFkbmhOY1kyTGgyQmxROVR2MFdDQjVSUmNlMTRfSXNtMm1SSUp2ZWJZc200T19MMnc1Y3BuZE1PLWFpVlA2VWJ3V3U1Q21JNWJMZndpY3g4SlpRN19BaVViTEh1aU5KTGljZ0htQXlUMVdMQTNyS3g4OHhKcjdibTlPSmhsVmJQRWFDZ1lLQWJZU0FSWVNGUUhHWDJNaTdOVEhsQnFfdW1SNVdZS0RpeUdJVGcwMjA2IiwgInJlZnJlc2hfdG9rZW4iOiAiMS8vMGdfM0FzNWRWaTJzRENnWUlBUkFBR0JBU053Ri1MOUlyQUZEMUh0TUpNbnp3NFdidTRqemFHeTVPdXVBNUdEQzNGb3I1ZHVsMnBTcmpibHFyMjZCbFlRdlNNNm12NVRac1FSUSIsICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCAiY2xpZW50X2lkIjogIjg4MDkzODE2MzA2My1nM2I5dmc2Nm03c3Q0Zm83bHJpMTBoZWFoYW1wdW1ubi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsICJjbGllbnRfc2VjcmV0IjogIkdPQ1NQWC10a3YxUUloMnZBUFEtOHk0UkRqSmIya0JlSjJQIiwgInNjb3BlcyI6IFsiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vYXV0aC9jYWxlbmRhci5yZWFkb25seSIsICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2dtYWlsLnJlYWRvbmx5Il0sICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iLCAiYWNjb3VudCI6ICIiLCAiZXhwaXJ5IjogIjIwMjYtMDctMzFUMTA6NDA6NThaIn0=
    healthCheckPath: /health

